### ISSUE TITLE
Separation of concern 

### ISSUE THREAD

**Issue by ghassanmas** [FACK1/languages-search#23]
The following snippet of code should be wrapped in a pure fuction that is testable, it's also  recommended if the function is written on the server-side instead of the server responding with the whole file. 
 
https://github.com/FACK1/languages-search/blob/c06fbcc40169728ad2f2ad482483f182ac6a95fa/public/main.js#L9-L21

**Comment by mattlub** [comment]
👍 for using `startsWith`
