### ISSUE TITLE
DOM and HTML overlapping 

### ISSUE THREAD

**Issue by ghassanmas** [FACK1/languages-search#39]
So according to the following HTML you are have `ul` elment with id of  `ulid` then in the js file you create the same element ul element with the same id and append it to the same parent in html ! 
https://github.com/FACK1/languages-search/blob/c06fbcc40169728ad2f2ad482483f182ac6a95fa/public/index.html#L16-L19

https://github.com/FACK1/languages-search/blob/c06fbcc40169728ad2f2ad482483f182ac6a95fa/public/main.js#L23-L33

**Comment by ghassanmas** [comment]
and the `body` tag is not closed in the html file

**Comment by amanshawar** [comment]
i fix this line done
